package fr.GCQuesne;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

import static fr.GCQuesne.ListAccount.myAccount;

public class AccountingRecordGUI {
  JPanel mainPanel;
  private JPanel itemTransactionPanel;
  private JPanel imagePanel;

  private JComboBox comboBox1;
  private JComboBox comboBox2;

  private JTextField transactionValueTextArea;
  private JTextField chequeNumberTextArea;

  private JButton debitBtn;
  private JButton creditBtn;

  private JLabel euroLabel;
  private JLabel valueLabel;
  private JLabel themeLabel;
  private JLabel typeTransactionLabel;
  private JLabel chequeNumberLabel;
  private JLabel lastNameLabel;
  private JLabel lastNameField;
  private JLabel firstNameLabel;
  private JLabel firstNameField;
  private JLabel lastNameSecondLabel;
  private JLabel firstNameSecondLabel;
  private JLabel lastNameSecondField;
  private JLabel firstNameSecondField;

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  public void createUIComponents() {
    itemTransactionPanel = new JPanel();
    itemTransactionPanel.setSize(0, 300);
    itemTransactionPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black),
        ("Compte " + myAccount.getAccountType() + " n° " + myAccount.getAccountNumber() + " : " + myAccount.getAccountValue() + " Euros"),
        TitledBorder.LEFT, TitledBorder.DEFAULT_POSITION, null, new Color(-14342875)));

    lastNameField = new JLabel();
    lastNameField.setText(myAccount.getClientLastName());

    firstNameField = new JLabel();
    firstNameField.setText(myAccount.getClientFirstName());

    lastNameSecondLabel = new JLabel();
    lastNameSecondLabel.setSize(100, 16);
    lastNameSecondLabel.setText("Nom :");
    lastNameSecondLabel.setForeground(new Color(-14342875));
    lastNameSecondLabel.setVisible(false);
    itemTransactionPanel.add(lastNameSecondLabel);

    firstNameSecondLabel = new JLabel();
    firstNameSecondLabel.setSize(100, 16);
    firstNameSecondLabel.setText("Prénom :");
    firstNameSecondLabel.setForeground(new Color(-14342875));
    firstNameSecondLabel.setVisible(false);
    itemTransactionPanel.add(firstNameSecondLabel);

    lastNameSecondField = new JLabel();
    lastNameSecondField.setSize(100, 16);
    lastNameSecondField.setText(myAccount.get);
    lastNameSecondField.setForeground(new Color(-14342875));
    lastNameSecondField.setVisible(false);
    itemTransactionPanel.add(lastNameSecondField);

    firstNameSecondField = new JLabel();
    firstNameSecondField.setSize(100, 16);
    firstNameSecondField.setText("test2");
    firstNameSecondField.setForeground(new Color(-14342875));
    firstNameSecondField.setVisible(false);
    itemTransactionPanel.add(firstNameSecondField);

    if (myAccount.getAccountType().equalsIgnoreCase("joint")) {
      lastNameSecondField.setVisible(true);
      lastNameSecondLabel.setVisible(true);

      firstNameSecondField.setVisible(true);
      firstNameSecondLabel.setVisible(true);

    } else {
      lastNameSecondLabel.setVisible(false);
      lastNameSecondField.setVisible(false);

      firstNameSecondLabel.setVisible(false);
      firstNameSecondField.setVisible(false);
      System.out.println("c'est pas un compte joint");
    }
  }

  /**
   Method generated by IntelliJ IDEA GUI Designer >>> IMPORTANT!! <<< DO NOT edit this method OR call
   it in your code!

   @noinspection ALL
   */
  private void $$$setupUI$$$() {
    createUIComponents();
    mainPanel = new JPanel();
    mainPanel.setLayout(new BorderLayout(0, 0));
    mainPanel.setBackground(new Color(-3100784));
    mainPanel.setForeground(new Color(-3100784));
    mainPanel.setMinimumSize(new Dimension(454, 600));
    mainPanel.setPreferredSize(new Dimension(450, 600));
    mainPanel.setVisible(true);
    imagePanel = new JPanel();
    imagePanel.setLayout(new BorderLayout(0, 0));
    imagePanel.setBackground(new Color(-3100784));
    imagePanel.setMinimumSize(new Dimension(454, 250));
    imagePanel.setPreferredSize(new Dimension(454, 250));
    mainPanel.add(imagePanel, BorderLayout.SOUTH);
    final JLabel label1 = new JLabel();
    label1.setIcon(new ImageIcon(getClass().getResource("/img/accountingRecord.png")));
    label1.setText("");
    imagePanel.add(label1, BorderLayout.CENTER);
    itemTransactionPanel.setLayout(new GridBagLayout());
    itemTransactionPanel.setBackground(new Color(-3100784));
    itemTransactionPanel.setEnabled(true);
    itemTransactionPanel.setMinimumSize(new Dimension(300, 300));
    itemTransactionPanel.setPreferredSize(new Dimension(450, 350));
    itemTransactionPanel.setVisible(true);
    mainPanel.add(itemTransactionPanel, BorderLayout.NORTH);
    valueLabel = new JLabel();
    valueLabel.setForeground(new Color(-14342875));
    valueLabel.setText("Valeur :");
    valueLabel.setVisible(true);
    GridBagConstraints gbc;
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 2;
    gbc.gridwidth = 3;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.insets = new Insets(20, 0, 15, 0);
    itemTransactionPanel.add(valueLabel, gbc);
    transactionValueTextArea = new JTextField();
    transactionValueTextArea.setBackground(new Color(-5468041));
    transactionValueTextArea.setCaretColor(new Color(-12514287));
    transactionValueTextArea.setForeground(new Color(-14342875));
    transactionValueTextArea.setMinimumSize(new Dimension(120, 30));
    transactionValueTextArea.setPreferredSize(new Dimension(150, 30));
    transactionValueTextArea.setVisible(true);
    gbc = new GridBagConstraints();
    gbc.gridx = 3;
    gbc.gridy = 2;
    gbc.gridwidth = 2;
    gbc.fill = GridBagConstraints.BOTH;
    gbc.insets = new Insets(20, 0, 15, 0);
    itemTransactionPanel.add(transactionValueTextArea, gbc);
    euroLabel = new JLabel();
    euroLabel.setForeground(new Color(-14342875));
    euroLabel.setText("Euros");
    euroLabel.setVisible(true);
    gbc = new GridBagConstraints();
    gbc.gridx = 5;
    gbc.gridy = 2;
    gbc.gridwidth = 2;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.insets = new Insets(20, 15, 15, 0);
    itemTransactionPanel.add(euroLabel, gbc);
    themeLabel = new JLabel();
    themeLabel.setForeground(new Color(-14342875));
    themeLabel.setText("Poste :");
    themeLabel.setVisible(true);
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 3;
    gbc.gridwidth = 3;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.insets = new Insets(15, 0, 15, 0);
    itemTransactionPanel.add(themeLabel, gbc);
    typeTransactionLabel = new JLabel();
    typeTransactionLabel.setForeground(new Color(-14342875));
    typeTransactionLabel.setText("Mode de paiement :");
    typeTransactionLabel.setVisible(true);
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 4;
    gbc.gridwidth = 3;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.insets = new Insets(0, 0, 0, 15);
    itemTransactionPanel.add(typeTransactionLabel, gbc);
    comboBox1 = new JComboBox();
    comboBox1.setBackground(new Color(-5468041));
    comboBox1.setForeground(new Color(-14342875));
    comboBox1.setMinimumSize(new Dimension(120, 30));
    final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
    defaultComboBoxModel1.addElement("Salaire");
    defaultComboBoxModel1.addElement("Loyer");
    defaultComboBoxModel1.addElement("Alimentation");
    defaultComboBoxModel1.addElement("Divers");
    comboBox1.setModel(defaultComboBoxModel1);
    comboBox1.setPreferredSize(new Dimension(150, 30));
    comboBox1.setVisible(true);
    gbc = new GridBagConstraints();
    gbc.gridx = 3;
    gbc.gridy = 3;
    gbc.gridwidth = 2;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    itemTransactionPanel.add(comboBox1, gbc);
    comboBox2 = new JComboBox();
    comboBox2.setBackground(new Color(-5468041));
    comboBox2.setForeground(new Color(-14342875));
    comboBox2.setMinimumSize(new Dimension(120, 30));
    final DefaultComboBoxModel defaultComboBoxModel2 = new DefaultComboBoxModel();
    defaultComboBoxModel2.addElement("Carte bancaire");
    defaultComboBoxModel2.addElement("Virement");
    defaultComboBoxModel2.addElement("Chèque");
    comboBox2.setModel(defaultComboBoxModel2);
    comboBox2.setPreferredSize(new Dimension(150, 30));
    comboBox2.setVisible(true);
    gbc = new GridBagConstraints();
    gbc.gridx = 3;
    gbc.gridy = 4;
    gbc.gridwidth = 2;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    itemTransactionPanel.add(comboBox2, gbc);
    debitBtn = new JButton();
    debitBtn.setBackground(new Color(-3100784));
    debitBtn.setForeground(new Color(-14342875));
    debitBtn.setText("Débit");
    debitBtn.setVisible(true);
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 6;
    gbc.gridwidth = 3;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    gbc.insets = new Insets(20, 0, 0, 0);
    itemTransactionPanel.add(debitBtn, gbc);
    chequeNumberTextArea = new JTextField();
    chequeNumberTextArea.setBackground(new Color(-5468041));
    chequeNumberTextArea.setCaretColor(new Color(-12514287));
    chequeNumberTextArea.setEnabled(true);
    chequeNumberTextArea.setForeground(new Color(-14342875));
    chequeNumberTextArea.setMinimumSize(new Dimension(120, 30));
    chequeNumberTextArea.setPreferredSize(new Dimension(150, 30));
    chequeNumberTextArea.setText("");
    chequeNumberTextArea.setVisible(true);
    gbc = new GridBagConstraints();
    gbc.gridx = 3;
    gbc.gridy = 5;
    gbc.gridwidth = 2;
    gbc.fill = GridBagConstraints.BOTH;
    gbc.insets = new Insets(15, 0, 15, 0);
    itemTransactionPanel.add(chequeNumberTextArea, gbc);
    creditBtn = new JButton();
    creditBtn.setBackground(new Color(-3100784));
    creditBtn.setForeground(new Color(-14342875));
    creditBtn.setText("Crédit");
    creditBtn.setVisible(true);
    gbc = new GridBagConstraints();
    gbc.gridx = 5;
    gbc.gridy = 6;
    gbc.gridwidth = 2;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    gbc.insets = new Insets(20, 0, 0, 0);
    itemTransactionPanel.add(creditBtn, gbc);
    chequeNumberLabel = new JLabel();
    chequeNumberLabel.setEnabled(true);
    chequeNumberLabel.setForeground(new Color(-14342875));
    chequeNumberLabel.setText("Numéro de chèque :");
    chequeNumberLabel.setVisible(true);
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 5;
    gbc.gridwidth = 3;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.insets = new Insets(0, 0, 0, 15);
    itemTransactionPanel.add(chequeNumberLabel, gbc);
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 1;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.insets = new Insets(15, 0, 0, 0);
    itemTransactionPanel.add(lastNameSecondLabel, gbc);
    lastNameLabel = new JLabel();
    lastNameLabel.setForeground(new Color(-14342875));
    lastNameLabel.setText("Nom :");
    lastNameLabel.setVisible(true);
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 0;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.insets = new Insets(15, 0, 0, 0);
    itemTransactionPanel.add(lastNameLabel, gbc);
    gbc = new GridBagConstraints();
    gbc.gridx = 4;
    gbc.gridy = 1;
    gbc.anchor = GridBagConstraints.EAST;
    gbc.insets = new Insets(15, 0, 0, 0);
    itemTransactionPanel.add(firstNameSecondLabel, gbc);
    firstNameLabel = new JLabel();
    firstNameLabel.setForeground(new Color(-14342875));
    firstNameLabel.setText("Prénom :");
    firstNameLabel.setVisible(true);
    gbc = new GridBagConstraints();
    gbc.gridx = 4;
    gbc.gridy = 0;
    gbc.gridwidth = 2;
    gbc.anchor = GridBagConstraints.EAST;
    gbc.insets = new Insets(15, 0, 0, 0);
    itemTransactionPanel.add(firstNameLabel, gbc);
    lastNameField.setForeground(new Color(-14342875));
    lastNameField.setMinimumSize(new Dimension(100, 16));
    lastNameField.setPreferredSize(new Dimension(110, 16));
    lastNameField.setVisible(true);
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 0;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.insets = new Insets(15, 5, 0, 0);
    itemTransactionPanel.add(lastNameField, gbc);
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 1;
    gbc.gridwidth = 2;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.insets = new Insets(15, 5, 0, 0);
    itemTransactionPanel.add(lastNameSecondField, gbc);
    firstNameField.setForeground(new Color(-14342875));
    firstNameField.setMinimumSize(new Dimension(100, 16));
    firstNameField.setPreferredSize(new Dimension(100, 16));
    firstNameField.setVisible(true);
    gbc = new GridBagConstraints();
    gbc.gridx = 6;
    gbc.gridy = 0;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.insets = new Insets(15, 5, 0, 0);
    itemTransactionPanel.add(firstNameField, gbc);
    gbc = new GridBagConstraints();
    gbc.gridx = 6;
    gbc.gridy = 1;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.insets = new Insets(15, 5, 0, 0);
    itemTransactionPanel.add(firstNameSecondField, gbc);
  }

  /** @noinspection ALL */
  public JComponent $$$getRootComponent$$$() {
    return mainPanel;
  }

}
