package fr.GCQuesne;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;

import static fr.GCQuesne.IndexAppliGUI.enteredAccount;
import static fr.GCQuesne.Project.myFileAccount;
import static fr.GCQuesne.Project.myListAccount;


public class CreateAccountGUI extends JWindow {
  public JPanel mainPanel;
  private JPanel idPanel;
  private JPanel typeAccountPanel;


  private JTextField lastNameField;
  private JTextField firstNameField;
  private JTextField initialValueField;
  private JTextField savingRateValueField;
  private JTextField lastNameSecondField;
  private JTextField firstNameSecondField;

  private JRadioButton currentTypeRadioBtn;
  private JRadioButton savingTypeRadioBtn;
  private JRadioButton joinTypeRadioBtn;

  private JLabel balanceInitialLabel;
  private JLabel euroLabel;
  private JLabel imgBackgroundAccount;
  private JLabel numberAccountSelectedLabel;
  private JLabel savingRateLabel;
  private JLabel lastNameLabel;
  private JLabel firstNameLabel;
  private JLabel lastNameSecondLabel;
  private JLabel firstNameSecondLabel;

  private JButton ValidateBtn;
  private JLabel percentageLabel;


  private ButtonGroup typeAccountBtnGroup;

  public CreateAccountGUI() {
    $$$setupUI$$$();
    ValidateBtn.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent e) {
        String firstName = firstNameField.getText();
        String lastName = lastNameField.getText();
        String firstNameSecond = firstNameSecondField.getText();
        String lastNameSecond = lastNameSecondField.getText();
        String accountNumber = numberAccountSelectedLabel.getText();
        String initialValue = initialValueField.getText();
        String savingRate = savingRateValueField.getText();

        if (typeAccountBtnGroup.isSelected(currentTypeRadioBtn.getModel())) {
          Account myAccount = new Account(lastName, firstName, "courant", accountNumber, initialValue);
          myListAccount.addAccount(myAccount);
          myFileAccount.saveAll(myListAccount);
        }

        if (typeAccountBtnGroup.isSelected(savingTypeRadioBtn.getModel())) {
          Account mySavingAccount = new SavingAccount(lastName, firstName, accountNumber, initialValue, savingRate);
          myListAccount.addAccount(mySavingAccount);
          myFileAccount.saveAll(myListAccount);
        }

        if (typeAccountBtnGroup.isSelected(joinTypeRadioBtn.getModel())) {
          Account myJoinAccount = new JoinAccount(lastName, firstName, lastNameSecond, firstNameSecond, accountNumber, initialValue);
          myListAccount.addAccount(myJoinAccount);
          myFileAccount.saveAll(myListAccount);
        }


        myListAccount.printAllAccounts();
      }
    });
    savingTypeRadioBtn.addItemListener(new ItemListener() {
      @Override
      public void itemStateChanged(ItemEvent e) {
        if (e.getStateChange() == ItemEvent.SELECTED) {
          savingRateLabel.setVisible(true);
          savingRateValueField.setVisible(true);
          percentageLabel.setVisible(true);
        } else {
          savingRateLabel.setVisible(false);
          savingRateValueField.setVisible(false);
          percentageLabel.setVisible(false);
        }
      }
    });

    joinTypeRadioBtn.addItemListener(new ItemListener() {
      @Override
      public void itemStateChanged(ItemEvent e) {
        if (e.getStateChange() == ItemEvent.SELECTED) {
          firstNameSecondLabel.setVisible(true);
          firstNameSecondField.setVisible(true);
          lastNameSecondLabel.setVisible(true);
          lastNameSecondField.setVisible(true);
        } else {
          firstNameSecondLabel.setVisible(false);
          firstNameSecondField.setVisible(false);
          lastNameSecondLabel.setVisible(false);
          lastNameSecondField.setVisible(false);
        }
      }
    });
  }

  public void createUIComponents() {
    numberAccountSelectedLabel = new JLabel();
    numberAccountSelectedLabel.setText(enteredAccount);

    typeAccountPanel = new JPanel();
    typeAccountPanel.setSize(0, 300);
    typeAccountPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), ("Compte n° : " + numberAccountSelectedLabel.getText() + " "), TitledBorder.LEFT,
        TitledBorder.DEFAULT_POSITION, this.$$$getFont$$$("Arial Rounded MT Bold", Font.BOLD | Font.ITALIC, 16, typeAccountPanel.getFont()), new Color(-14342875)));
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer >>> IMPORTANT!! <<< DO NOT edit this method OR call it in your
   * code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    createUIComponents();
    mainPanel = new JPanel();
    mainPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
    mainPanel.setBackground(new Color(-3100784));
    mainPanel.setPreferredSize(new Dimension(450, 700));
    idPanel = new JPanel();
    idPanel.setLayout(new GridBagLayout());
    idPanel.setAlignmentY(0.5f);
    idPanel.setBackground(new Color(-3100784));
    mainPanel.add(idPanel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(300, 150), null, 0, false));
    idPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), "Identification", TitledBorder.LEADING, TitledBorder.TOP, this.$$$getFont$$$("Arial Rounded MT Bold", Font.BOLD | Font.ITALIC, 16, idPanel.getFont()), new Color(-14342875)));
    lastNameLabel = new JLabel();
    lastNameLabel.setForeground(new Color(-14342875));
    lastNameLabel.setHorizontalAlignment(2);
    lastNameLabel.setText("Nom :");
    GridBagConstraints gbc;
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 0;
    gbc.anchor = GridBagConstraints.WEST;
    idPanel.add(lastNameLabel, gbc);
    firstNameLabel = new JLabel();
    firstNameLabel.setForeground(new Color(-14342875));
    firstNameLabel.setHorizontalAlignment(2);
    firstNameLabel.setText("Prénom :");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 1;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.fill = GridBagConstraints.VERTICAL;
    idPanel.add(firstNameLabel, gbc);
    firstNameField = new JTextField();
    firstNameField.setBackground(new Color(-5468041));
    firstNameField.setMinimumSize(new Dimension(200, 30));
    firstNameField.setPreferredSize(new Dimension(200, 30));
    firstNameField.setText("");
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 1;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    gbc.insets = new Insets(25, 15, 25, 0);
    idPanel.add(firstNameField, gbc);
    lastNameField = new JTextField();
    lastNameField.setBackground(new Color(-5468041));
    lastNameField.setMinimumSize(new Dimension(200, 30));
    lastNameField.setPreferredSize(new Dimension(200, 30));
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 0;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    gbc.insets = new Insets(25, 15, 25, 0);
    idPanel.add(lastNameField, gbc);
    lastNameSecondLabel = new JLabel();
    lastNameSecondLabel.setForeground(new Color(-14342875));
    lastNameSecondLabel.setHorizontalAlignment(2);
    lastNameSecondLabel.setText("Nom :");
    lastNameSecondLabel.setVisible(false);
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 2;
    gbc.anchor = GridBagConstraints.WEST;
    idPanel.add(lastNameSecondLabel, gbc);
    firstNameSecondLabel = new JLabel();
    firstNameSecondLabel.setForeground(new Color(-14342875));
    firstNameSecondLabel.setHorizontalAlignment(2);
    firstNameSecondLabel.setText("Prénom :");
    firstNameSecondLabel.setVisible(false);
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 3;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.fill = GridBagConstraints.VERTICAL;
    idPanel.add(firstNameSecondLabel, gbc);
    lastNameSecondField = new JTextField();
    lastNameSecondField.setBackground(new Color(-5468041));
    lastNameSecondField.setMinimumSize(new Dimension(200, 30));
    lastNameSecondField.setPreferredSize(new Dimension(200, 30));
    lastNameSecondField.setVisible(false);
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 2;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    gbc.insets = new Insets(25, 15, 25, 0);
    idPanel.add(lastNameSecondField, gbc);
    firstNameSecondField = new JTextField();
    firstNameSecondField.setBackground(new Color(-5468041));
    firstNameSecondField.setMinimumSize(new Dimension(200, 30));
    firstNameSecondField.setPreferredSize(new Dimension(200, 30));
    firstNameSecondField.setText("");
    firstNameSecondField.setVisible(false);
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 3;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    gbc.insets = new Insets(25, 15, 25, 0);
    idPanel.add(firstNameSecondField, gbc);
    typeAccountPanel.setLayout(new GridBagLayout());
    typeAccountPanel.setBackground(new Color(-3100784));
    typeAccountPanel.setForeground(new Color(-14342875));
    mainPanel.add(typeAccountPanel, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(-1, 80), null, 0, false));
    currentTypeRadioBtn = new JRadioButton();
    currentTypeRadioBtn.setBackground(new Color(-3100784));
    currentTypeRadioBtn.setEnabled(true);
    currentTypeRadioBtn.setForeground(new Color(-14342875));
    currentTypeRadioBtn.setSelected(true);
    currentTypeRadioBtn.setText("Compte Courant");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 0;
    gbc.gridwidth = 2;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.insets = new Insets(15, 15, 20, 0);
    typeAccountPanel.add(currentTypeRadioBtn, gbc);
    savingTypeRadioBtn = new JRadioButton();
    savingTypeRadioBtn.setBackground(new Color(-3100784));
    savingTypeRadioBtn.setForeground(new Color(-14342875));
    savingTypeRadioBtn.setSelected(false);
    savingTypeRadioBtn.setText("Compte Epargne");
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 0;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.insets = new Insets(15, 20, 20, 20);
    typeAccountPanel.add(savingTypeRadioBtn, gbc);
    joinTypeRadioBtn = new JRadioButton();
    joinTypeRadioBtn.setBackground(new Color(-3100784));
    joinTypeRadioBtn.setForeground(new Color(-14342875));
    joinTypeRadioBtn.setText("Compte Joint");
    joinTypeRadioBtn.setVisible(true);
    gbc = new GridBagConstraints();
    gbc.gridx = 3;
    gbc.gridy = 0;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.insets = new Insets(15, 0, 20, 15);
    typeAccountPanel.add(joinTypeRadioBtn, gbc);
    euroLabel = new JLabel();
    euroLabel.setForeground(new Color(-14342875));
    euroLabel.setText("euros");
    gbc = new GridBagConstraints();
    gbc.gridx = 3;
    gbc.gridy = 2;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.insets = new Insets(15, 15, 20, 0);
    typeAccountPanel.add(euroLabel, gbc);
    initialValueField = new JTextField();
    initialValueField.setBackground(new Color(-5468041));
    initialValueField.setForeground(new Color(-14342875));
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 2;
    gbc.fill = GridBagConstraints.BOTH;
    gbc.insets = new Insets(15, 0, 20, 0);
    typeAccountPanel.add(initialValueField, gbc);
    balanceInitialLabel = new JLabel();
    balanceInitialLabel.setForeground(new Color(-14342875));
    balanceInitialLabel.setText("Solde :");
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 2;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.insets = new Insets(15, 15, 20, 15);
    typeAccountPanel.add(balanceInitialLabel, gbc);
    savingRateValueField = new JTextField();
    savingRateValueField.setBackground(new Color(-5468041));
    savingRateValueField.setForeground(new Color(-14342875));
    savingRateValueField.setVisible(false);
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 1;
    gbc.fill = GridBagConstraints.BOTH;
    gbc.insets = new Insets(15, 0, 20, 0);
    typeAccountPanel.add(savingRateValueField, gbc);
    savingRateLabel = new JLabel();
    savingRateLabel.setForeground(new Color(-14342875));
    savingRateLabel.setText("Taux d'épagne :");
    savingRateLabel.setVisible(false);
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 1;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.insets = new Insets(15, 15, 20, 15);
    typeAccountPanel.add(savingRateLabel, gbc);
    percentageLabel = new JLabel();
    percentageLabel.setForeground(new Color(-14342875));
    percentageLabel.setText("%");
    percentageLabel.setVisible(false);
    gbc = new GridBagConstraints();
    gbc.gridx = 3;
    gbc.gridy = 1;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.insets = new Insets(15, 15, 20, 15);
    typeAccountPanel.add(percentageLabel, gbc);
    ValidateBtn = new JButton();
    ValidateBtn.setBackground(new Color(-3100784));
    ValidateBtn.setForeground(new Color(-14342875));
    ValidateBtn.setText("Confirmer");
    gbc = new GridBagConstraints();
    gbc.gridx = 3;
    gbc.gridy = 3;
    gbc.insets = new Insets(0, 0, 20, 0);
    typeAccountPanel.add(ValidateBtn, gbc);
    final JPanel panel1 = new JPanel();
    panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    panel1.setBackground(new Color(-3100784));
    mainPanel.add(panel1, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    imgBackgroundAccount = new JLabel();
    imgBackgroundAccount.setAlignmentY(1.0f);
    imgBackgroundAccount.setAutoscrolls(false);
    imgBackgroundAccount.setBackground(new Color(-3100784));
    imgBackgroundAccount.setIcon(new ImageIcon(getClass().getResource("/img/create_account.png")));
    imgBackgroundAccount.setIconTextGap(0);
    imgBackgroundAccount.setInheritsPopupMenu(false);
    imgBackgroundAccount.setOpaque(false);
    imgBackgroundAccount.setText("");
    imgBackgroundAccount.setVerticalAlignment(1);
    imgBackgroundAccount.setVerticalTextPosition(1);
    panel1.add(imgBackgroundAccount, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTHWEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, new Dimension(350, 300), new Dimension(450, 500), new Dimension(500, 300), 0, false));
    typeAccountBtnGroup = new ButtonGroup();
    typeAccountBtnGroup.add(currentTypeRadioBtn);
    typeAccountBtnGroup.add(savingTypeRadioBtn);
    typeAccountBtnGroup.add(joinTypeRadioBtn);
  }

  /** @noinspection ALL */
  private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
    if (currentFont == null) return null;
    String resultName;
    if (fontName == null) {
      resultName = currentFont.getName();
    } else {
      Font testFont = new Font(fontName, Font.PLAIN, 10);
      if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
        resultName = fontName;
      } else {
        resultName = currentFont.getName();
      }
    }
    return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
  }

  /** @noinspection ALL */
  public JComponent $$$getRootComponent$$$() {
    return mainPanel;
  }


}
