package fr.GCQuesne;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

public class PrintLineAccountGUI {


  public JPanel mainPanel;
  public JPanel contentTablePanel;
  public JButton validateBtn;
  public JLabel backgroundImageLabel;


  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  private void createUIComponents() {

  }

  /**
   Method generated by IntelliJ IDEA GUI Designer >>> IMPORTANT!! <<< DO NOT edit this method OR call
   it in your code!

   @noinspection ALL
   */
  private void $$$setupUI$$$() {
    mainPanel = new JPanel();
    mainPanel.setLayout(new BorderLayout(0, 0));
    mainPanel.setBackground(new Color(-3100784));
    mainPanel.setPreferredSize(new Dimension(500, 600));
    contentTablePanel = new JPanel();
    contentTablePanel.setLayout(new GridBagLayout());
    contentTablePanel.setBackground(new Color(-3100784));
    mainPanel.add(contentTablePanel, BorderLayout.NORTH);
    contentTablePanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
    final JLabel label1 = new JLabel();
    Font label1Font = this.$$$getFont$$$("Arial Rounded MT Bold", Font.BOLD, 14, label1.getFont());
    if (label1Font != null) label1.setFont(label1Font);
    label1.setForeground(new Color(-14342875));
    label1.setHorizontalAlignment(0);
    label1.setHorizontalTextPosition(0);
    label1.setIconTextGap(0);
    label1.setPreferredSize(new Dimension(150, 25));
    label1.setText("Poste");
    GridBagConstraints gbc;
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 0;
    contentTablePanel.add(label1, gbc);
    final JLabel label2 = new JLabel();
    Font label2Font = this.$$$getFont$$$("Arial Rounded MT Bold", Font.BOLD, 14, label2.getFont());
    if (label2Font != null) label2.setFont(label2Font);
    label2.setForeground(new Color(-14342875));
    label2.setHorizontalAlignment(0);
    label2.setHorizontalTextPosition(0);
    label2.setIconTextGap(0);
    label2.setPreferredSize(new Dimension(150, 25));
    label2.setText("Mode de Paiement");
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 0;
    contentTablePanel.add(label2, gbc);
    final JLabel label3 = new JLabel();
    Font label3Font = this.$$$getFont$$$("Arial Rounded MT Bold", Font.BOLD, 14, label3.getFont());
    if (label3Font != null) label3.setFont(label3Font);
    label3.setForeground(new Color(-14342875));
    label3.setHorizontalAlignment(0);
    label3.setHorizontalTextPosition(0);
    label3.setIconTextGap(0);
    label3.setPreferredSize(new Dimension(150, 25));
    label3.setText("Valeur");
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 0;
    contentTablePanel.add(label3, gbc);
    final JLabel label4 = new JLabel();
    label4.setForeground(new Color(-14342875));
    label4.setHorizontalAlignment(0);
    label4.setPreferredSize(new Dimension(150, 18));
    label4.setText("{{typeTransaction}}");
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 2;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.insets = new Insets(0, 0, 15, 0);
    contentTablePanel.add(label4, gbc);
    final JLabel label5 = new JLabel();
    label5.setForeground(new Color(-14342875));
    label5.setHorizontalAlignment(0);
    label5.setPreferredSize(new Dimension(150, 18));
    label5.setText("{{valueTransaction}}");
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 2;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.insets = new Insets(0, 0, 15, 0);
    contentTablePanel.add(label5, gbc);
    final JLabel label6 = new JLabel();
    label6.setForeground(new Color(-14342875));
    label6.setHorizontalAlignment(0);
    label6.setPreferredSize(new Dimension(150, 18));
    label6.setText("{{typeTransaction}}");
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 3;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.insets = new Insets(0, 0, 15, 0);
    contentTablePanel.add(label6, gbc);
    final JLabel label7 = new JLabel();
    label7.setForeground(new Color(-14342875));
    label7.setHorizontalAlignment(0);
    label7.setPreferredSize(new Dimension(150, 18));
    label7.setText("{{themeTransaction4}}");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 4;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.insets = new Insets(0, 0, 15, 0);
    contentTablePanel.add(label7, gbc);
    final JLabel label8 = new JLabel();
    label8.setForeground(new Color(-14342875));
    label8.setHorizontalAlignment(0);
    label8.setPreferredSize(new Dimension(150, 18));
    label8.setText("{{themeTransaction5}}");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 5;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.insets = new Insets(0, 0, 15, 0);
    contentTablePanel.add(label8, gbc);
    final JLabel label9 = new JLabel();
    label9.setForeground(new Color(-14342875));
    label9.setHorizontalAlignment(0);
    label9.setPreferredSize(new Dimension(150, 18));
    label9.setText("{{valueTransaction}}");
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 6;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.insets = new Insets(0, 0, 15, 0);
    contentTablePanel.add(label9, gbc);
    final JLabel label10 = new JLabel();
    label10.setForeground(new Color(-14342875));
    label10.setHorizontalAlignment(0);
    label10.setPreferredSize(new Dimension(150, 18));
    label10.setText("{{valueTransaction}}");
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 5;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.insets = new Insets(0, 0, 15, 0);
    contentTablePanel.add(label10, gbc);
    final JLabel label11 = new JLabel();
    label11.setForeground(new Color(-14342875));
    label11.setHorizontalAlignment(0);
    label11.setPreferredSize(new Dimension(150, 18));
    label11.setText("{{valueTransaction}}");
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 4;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.insets = new Insets(0, 0, 15, 0);
    contentTablePanel.add(label11, gbc);
    final JLabel label12 = new JLabel();
    label12.setForeground(new Color(-14342875));
    label12.setHorizontalAlignment(0);
    label12.setPreferredSize(new Dimension(150, 18));
    label12.setText("{{valueTransaction}}");
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 3;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.insets = new Insets(0, 0, 15, 0);
    contentTablePanel.add(label12, gbc);
    final JLabel label13 = new JLabel();
    label13.setForeground(new Color(-14342875));
    label13.setHorizontalAlignment(0);
    label13.setPreferredSize(new Dimension(150, 18));
    label13.setText("{{typeTransaction}}");
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 4;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.insets = new Insets(0, 0, 15, 0);
    contentTablePanel.add(label13, gbc);
    final JLabel label14 = new JLabel();
    label14.setForeground(new Color(-14342875));
    label14.setHorizontalAlignment(0);
    label14.setPreferredSize(new Dimension(150, 18));
    label14.setText("{{typeTransaction}}");
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 5;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.insets = new Insets(0, 0, 15, 0);
    contentTablePanel.add(label14, gbc);
    final JLabel label15 = new JLabel();
    label15.setForeground(new Color(-14342875));
    label15.setHorizontalAlignment(0);
    label15.setPreferredSize(new Dimension(150, 18));
    label15.setText("{{typeTransaction}}");
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 6;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.insets = new Insets(0, 0, 15, 0);
    contentTablePanel.add(label15, gbc);
    final JLabel label16 = new JLabel();
    label16.setForeground(new Color(-14342875));
    label16.setHorizontalAlignment(0);
    label16.setPreferredSize(new Dimension(150, 18));
    label16.setText("{{themeTransaction1}}");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 1;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.insets = new Insets(0, 0, 15, 0);
    contentTablePanel.add(label16, gbc);
    final JLabel label17 = new JLabel();
    label17.setForeground(new Color(-14342875));
    label17.setHorizontalAlignment(0);
    label17.setPreferredSize(new Dimension(150, 18));
    label17.setText("{{themeTransaction2}}");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 2;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.insets = new Insets(0, 0, 15, 0);
    contentTablePanel.add(label17, gbc);
    final JLabel label18 = new JLabel();
    label18.setForeground(new Color(-14342875));
    label18.setHorizontalAlignment(0);
    label18.setPreferredSize(new Dimension(150, 18));
    label18.setText("{{themeTransaction3}}");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 3;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.insets = new Insets(0, 0, 15, 0);
    contentTablePanel.add(label18, gbc);
    final JLabel label19 = new JLabel();
    label19.setForeground(new Color(-14342875));
    label19.setHorizontalAlignment(0);
    label19.setPreferredSize(new Dimension(150, 18));
    label19.setText("{{themeTransaction6}}");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 6;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.insets = new Insets(0, 0, 15, 0);
    contentTablePanel.add(label19, gbc);
    final JLabel label20 = new JLabel();
    label20.setForeground(new Color(-14342875));
    label20.setHorizontalAlignment(0);
    label20.setPreferredSize(new Dimension(150, 18));
    label20.setText("{{typeTransaction}}");
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 1;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.insets = new Insets(0, 0, 15, 0);
    contentTablePanel.add(label20, gbc);
    final JLabel label21 = new JLabel();
    label21.setForeground(new Color(-14342875));
    label21.setHorizontalAlignment(0);
    label21.setPreferredSize(new Dimension(150, 18));
    label21.setText("{{valueTransaction}}");
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 1;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.insets = new Insets(0, 0, 15, 0);
    contentTablePanel.add(label21, gbc);
    final JPanel panel1 = new JPanel();
    panel1.setLayout(new GridBagLayout());
    panel1.setBackground(new Color(-3100784));
    mainPanel.add(panel1, BorderLayout.EAST);
    final JLabel label22 = new JLabel();
    label22.setEnabled(true);
    label22.setForeground(new Color(-14342875));
    label22.setText("Valeur :");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 0;
    gbc.anchor = GridBagConstraints.WEST;
    panel1.add(label22, gbc);
    final JLabel label23 = new JLabel();
    label23.setForeground(new Color(-14342875));
    label23.setText("{{currentValue}}");
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 0;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.insets = new Insets(0, 30, 0, 30);
    panel1.add(label23, gbc);
    final JLabel label24 = new JLabel();
    label24.setForeground(new Color(-14342875));
    label24.setText("Euros");
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 0;
    gbc.anchor = GridBagConstraints.WEST;
    panel1.add(label24, gbc);
    validateBtn = new JButton();
    validateBtn.setBackground(new Color(-5468041));
    validateBtn.setForeground(new Color(-14342875));
    validateBtn.setPreferredSize(new Dimension(100, 30));
    validateBtn.setText("OK");
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 1;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    gbc.insets = new Insets(20, 0, 0, 50);
    panel1.add(validateBtn, gbc);
    final JPanel panel2 = new JPanel();
    panel2.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    panel2.setBackground(new Color(-3100784));
    mainPanel.add(panel2, BorderLayout.SOUTH);
    backgroundImageLabel = new JLabel();
    backgroundImageLabel.setBackground(new Color(-3100784));
    backgroundImageLabel.setIcon(new ImageIcon(getClass().getResource("/img/accountingRecordPrint.png")));
    backgroundImageLabel.setText("");
    panel2.add(backgroundImageLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
  }

  /** @noinspection ALL */
  private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
    if (currentFont == null) return null;
    String resultName;
    if (fontName == null) {
      resultName = currentFont.getName();
    } else {
      Font testFont = new Font(fontName, Font.PLAIN, 10);
      if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
        resultName = fontName;
      } else {
        resultName = currentFont.getName();
      }
    }
    return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
  }

  /** @noinspection ALL */
  public JComponent $$$getRootComponent$$$() {
    return mainPanel;
  }
}
